version: '3.7'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

  movies:
    build: ./movies
    image: cinema/movies
    container_name: cinema-movies
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: movies.local

  bookings:
    build: ./bookings
    image: cinema/bookings
    container_name: cinema-bookings
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: bookings.local

  showtimes:
    build: ./showtimes
    image: cinema/showtimes
    container_name: cinema-showtimes
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: showtimes.local

  users:
    build: ./users
    image: cinema/users
    container_name: cinema-users
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: users.local

  db:
    image: mongo:3.3
    container_name: cinema-db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./backup
        target: /backup